blb_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestion.urls'))
]

gestion/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", index, name="index"),

    # Path class view
    path('libros_list/', LibroListView.as_view(), name="libros_list"),
    
    # Gestion Usuarios
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name="logout"),
    
    # cambio de contraseña
    path('password/change', auth_views.PasswordChangeView.as_view(), name="password_change"),
    path('password/change/done', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    
    path('registro/', registro, name="registro"),
    # libros
    path('libros/', lista_libros, name="lista_libros"),
    path('libros/nuevo/', crear_libro, name="crear_libro"),
    
    # Autores
    path('autores/', lista_autores, name="lista_autores"),
    path('autores/nuevo/', crear_autor, name="crear_autores"),
    path('autores/<int:id>/editar/', crear_autor, name="editar_autor"),
    
    # prestamos
    path('prestamos/', lista_prestamos, name="lista_prestamos"),
    path('prestamos/nuevo/', crear_prestamo, name="crear_prestamo"),
    path('prestamos/<int:id>', detalle_prestamo, name="detalle_prestamo"),

    # multas
    path('multas/', lista_multas, name="lista_multa"),
    path('multas/nuevo/<int:prestamo_id>', crear_multa, name="crear_multa"),
]

gestion/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class Autor(models.Model):
    nombre = models.CharField(max_length=150)
    apellido = models.CharField(max_length=50)
    bibliografia = models.CharField(max_length=200,blank=True, null=True)
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
class Libro(models.Model):
    titulo = models.CharField(max_length=20)
    autor = models.ForeignKey(Autor,related_name="libros", on_delete=models.PROTECT)
    disponible = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.titulo} {self.autor}"
    
class Prestamo(models.Model):
    libro = models.ForeignKey(Libro, related_name="prestamos", on_delete=models.PROTECT)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="prestamos", on_delete=models.PROTECT)
    fecha_prestamos = models.DateField(default=timezone.now)
    fecha_max = models.DateField()
    fecha_devolucion = models.DateField(blank=True, null=True)
    
    class Meta:
        permissions = (
            ("Ver_prestamos", "Puede ver prestamos"),
            ("gestionar_prestamos", "Puede gestionar prestamos"),
        )
    
    def __str__(self):
        return f"prestamo de {self.libro} a {self.usuario}"
    
    @property
    def dias_retraso(self):
        hoy = timezone.now().date()
        fecha_ref = self.fecha_devolucion or hoy
        if fecha_ref >= self.fecha_max:
            return (fecha_ref - self.fecha_max).days
        
    @property
    def multa_retraso(self):
        tarifa = 0.50
        return self.dias_retraso * tarifa
    
class Multa(models.Model):
    prestamo = models.ForeignKey(Prestamo, related_name="multas", on_delete=models.PROTECT)
    tipo = models.CharField(max_length=10, choices=(('r', 'retraso'),('p', 'perdida'),('d','deterioro')))
    monto = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    pagada = models.BooleanField(default=False)
    fecha = models.DateField(default=timezone.now)
    
    def __str__(self):
        return f"Multa {self.tipo} - {self.monto} - {self.prestamo}"

    def save(self, *args, **kwargs):
        if self.tipo == 'r' and self.monto == 0:
            self.monto = self.prestamo.multa_retraso
        super().save(*args, **kwargs)

gestion/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from django.http import HttpResponseForbidden
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import Group


from .models import Autor, Libro, Prestamo, Multa

def index(request):
    titulo2 = "Hola Mundo"
    title = settings.TITLE
    return render(request, 'gestion/templates/home.html', {'titulo': title, 't': titulo2})

def lista_libros(request):
    libros = Libro.objects.all()
    return render(request, 'gestion/templates/libros.html', {'libros': libros} )

def crear_libro(request):
    autores = Autor.objects.all()
    if request.method == "POST":
        titulo =  request.POST.get('titulo')
        autor_id =  request.POST.get('autor')
        
        if titulo and autor_id:
            autor = get_object_or_404(Autor, id=autor_id)
            Libro.objects.create(titulo=titulo, autor=autor)
            return redirect('lista_libros')
    return render(request, 'gestion/templates/crear_libros.html', {'autores': autores})

def lista_autores(request):
    autores = Autor.objects.all()
    return render(request, 'gestion/templates/autores.html', {'autores': autores} )

@login_required
def crear_autor(request, id=None):
    if id == None:
        autor = None
        modo = 'crear'
    else:
        autor = get_object_or_404(Autor, id=id)
        modo = 'editar'
        
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        apellido = request.POST.get('apellido')
        bibliografia = request.POST.get('bibliografia')
        if autor == None:
            Autor.objects.create(nombre=nombre, apellido=apellido, bibliografia=bibliografia)
        else:
            autor.apellido = apellido
            autor.nombre = nombre
            autor.bibliografia = bibliografia
            autor.save()
        return redirect('lista_autores')
    context = {'autor': autor,
               'titulo': 'Editar Autor' if modo == 'editar' else 'Crear Autor',
               'texto_boton': 'Guardar cambios' if modo == 'editar' else 'Crear'}
    return render(request, 'gestion/templates/crear_autores.html', context)

def lista_prestamos(request):
    prestamos = Prestamo.objects.all()
    return render(request, 'gestion/templates/prestamos.html', {'prestamos': prestamos} )


def crear_prestamo(request):
    if not request.user.has_perm('gestion.gestionar_prestamos'):
        return HttpResponseForbidden()
    libro = Libro.objects.filter(disponible=True)
    usuario = User.objects.all()
    if request.method == 'POST':
        libro_id = request.POST.get('libro')
        usuario_id = request.POST.get('usuario')
        fecha_prestamos = request.POST.get('fecha_prestamos')
        fecha_max = request.POST.get('fecha_max')

        if libro_id and usuario_id and fecha_prestamos and fecha_max:
            libro = get_object_or_404(Libro, id=libro_id)
            usuario = get_object_or_404(User, id=usuario_id)
            prestamo = Prestamo.objects.create(libro = libro,
                                               usuario=usuario,
                                               fecha_prestamos=fecha_prestamos,
                                               fecha_max=fecha_max)
            libro.disponible = False
            libro.save()
            return redirect('lista_prestamo', id=prestamo.id)
    fecha = (timezone.now().date()).isoformat() # YYYY-MM-DD
    return render(request, 'gestion/templates/crear_prestamo.html', {'libros': libro,
                                                                     'usuarios': usuario,
                                                                     'fecha': fecha})

def detalle_prestamo(request):
    pass

def lista_multas(request):
    multas = Multa.objects.all()
    return render(request, 'multas.html', {'multas': multas} )

def crear_multa(request):
    pass


def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            usuario = form.save()

            grupo = Group.objects.get(name="UsuariosBiblioteca")
            usuario.groups.add(grupo)

            login(request, usuario)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'gestion/templates/registration/registro.html', {'form': form})

# Create your views here.

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy

class LibroListView(LoginRequiredMixin, ListView):
    model = Libro
    template_name = 'gestion/templates/libros_view.html'
    context_object_name = 'libros'
    paginate_by = 10

class LibroDetalleView(LoginRequiredMixin, DetailView):
    model = Libro
    template_name = 'gestion/templates/detalle_libros.html'
    context_object_name = 'libros'

class LibroCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Libro
    fields = ['titulo', 'autor', 'disponible']
    template_name = 'gestion/templates/crear_libros.html'
    success_url = reverse_lazy('libro_list') # click url
    permission_required = 'gestion.add_libro' # permiso por defecto de django

class LibroUpdateView(LoginRequiredMixin, UpdateView, PermissionRequiredMixin):
    model = Libro
    fields = ['titulo', 'autor']
    template_name = 'gestion/templates/editar_libros.html'
    success_url = reverse_lazy('libro_list') 
    permission_required = 'gestion.change_libro' # actualizar, permiso de actualizar

class LibroDeleteView(LoginRequiredMixin, DeleteView, PermissionRequiredMixin):
    model = Libro
    template_name = 'gestion/templates/delete_libros.html'
    success_url = reverse_lazy('libro_list') 
    permission_required = 'gestion.delete_libro'

    
        
    

gestion/templates/autores.html
{% extends "index.html" %}

{% block contenido %}
<h2> AUTORES </h2>
    <table style="border: 1px solid">
        <tr style="border: 1px solid">
            <td style="border: 1px solid">Nombre</td>
            <td style="border: 1px solid">Apellido</td>
            <td style="border: 1px solid">Bibliografía</td>
            
            <td style="border: 1px solid"></td> 
        </tr>
        {% for autor in autores %}
        <tr style="border: 1px solid">
            <td style="border: 1px solid">
                {{ autor.nombre }}
            </td>
            <td style="border: 1px solid">
                {{ autor.apellido }}
            </td>
            <td style="border: 1px solid">
                {{ autor.bibliografia}}
            </td>
            
            <td style="border: 1px solid">
                {% if user.is_superuser %}
                    <a href="{% url 'editar_autor' autor.id %}">Editar</a>
                {% else %}
                    Sin permiso
                {% endif %}
            </td>
            
            </tr>
        {% endfor %}

    </table>

{% endblock %}

gestion/templates/crear_autores.html
{% extends "index.html" %}

<!-- Seccion de autores -->
{% block contenido %}
<h2> {{ titulo }}</h2>

<form method="POST">
    {% csrf_token %}
    <label for="id_nombre" name="nombre">Nombre: </label>
    <input type="text" id="id_nombre" name="nombre" value="{{ autor.nombre | default_if_none:'' }}" required><br/>

    <label for="id_apellido" name="apellido">Apellido: </label>
    <input type="text" id="id_apellido" name="apellido" value="{{ autor.apellido | default_if_none:'' }}" required><br/>

    <label for="id_bibliografia" name="bibliografia">Bibliografia: </label>
    <input type="text" id="id_bibliografia" name="bibliografia" value="{{ autor.bibliografia | default_if_none:'' }}" required><br/>

    <button type="submit"> {{ texto_boton }}</button>
</form>
{% endblock %}

gestion/templates/crear_libros.html
{% extends "index.html" %}

<!-- Seccion de autores -->
{% block contenido %}
<h2> Crear libros </h2>

<form method="POST">
    {% csrf_token %}
    <label for="id_titulo" name="titulo">Titulo: </label>
    <input type="text" id="id_titulo" name="titulo" required><br/>

    <label for="id_autor" name="autor">Autor: </label>
    <select id="id_autor" name="autor" required>
        <option value="">-- Selecione un autor --</option>
        {% for autor in autores %}
        <option value="{{ autor.id }}"> 
            {{ autor.nombre }} - {{ autor.apellido }}
        </option>
        {% endfor %}
    </select>
    

    <button type="submit">Guardar</button>
</form>
{% endblock %}

gestion/templates/crear_prestamo.html
{% extends "index.html" %}

<!-- Seccion de autores -->
{% block contenido %}
<h2>Crear Prestamo</h2>

<form method="POST">
    {% csrf_token %}
    <label for="id_libro" name="libro">Libro: </label>
    <select type="text" id="id_libro" name="libro" required><br/>
        <option value="">--Seleccionar Libro--</option>
        {% for libro in libros %}
            <option value="{{ libro.id }}">{{libro.titulo}}</option>
        {% endfor %}
    </select></br>

    <label for="id_usuario" name="autor">Usuario: </label>
    <select type="text" id="id_usuario" name="usuario" required><br/>
        <option value="">--Seleccionar Usuario--</option>
        {% for usuario in usuarios %}
            <option value="{{ usuario.id }}">{{usuario.username}}</option>
        {% endfor %}
    </select></br>
    <label for="id_fecha_prestamo" name="fecha_prestamo">Fecha Prestamo: </label>
    <input type="date" id="id_fecha_prestamo" name="fecha_prestamo" value="{{ fecha }}" required><br/>

    <button type="submit">Crear</button>

</form>

{% endblock %}

gestion/templates/crear_prestamos.html
{% extends "index.html" %}

<!-- Seccion de autores -->
{% block contenido %}
<h2>Crear Prestamo</h2>

<form method="POST">
    {% csrf_token %}
    <label for="id_libro" name="libro">Libro: </label>
    <select type="text" id="id_libro" name="libro" required><br/>
        <option value="">--Seleccionar Libro--</option>
        {% for libro in libros %}
            <option value="{{ libro.id }}">{{libro.titulo}}</option>
        {% endfor %}
    </select></br>

    <label for="id_usuario" name="autor">Usuario: </label>
    <select type="text" id="id_usuario" name="usuario" required><br/>
        <option value="">--Seleccionar Usuario--</option>
        {% for usuario in usuarios %}
            <option value="{{ usuario.id }}">{{usuario.username}}</option>
        {% endfor %}
    </select></br>
    <label for="id_fecha_prestamo" name="fecha_prestamo">Fecha Prestamo: </label>
    <input type="date" id="id_fecha_prestamo" name="fecha_prestamo" value="{{ fecha }}" required><br/>

    <button type="submit">Crear</button>

</form>

{% endblock %}

gestion/templates/home.html
{% extends "index.html" %}

{% block contenido %}
<div class="row g-4">
    <!-- Libros -->
    <div class="col-md-3">
        <div class="card shadow-sm text-center p-3">
            <i class="bi bi-journal-bookmark fs-1 text-primary"></i>
            <h4 class="mt-3">Libros</h4>
            <p>Administrar catálogo de libros.</p>
            <a href="#" class="btn btn-primary">Entrar</a>
        </div>
    </div>

    <!-- Autores -->
    <div class="col-md-3">
        <div class="card shadow-sm text-center p-3">
            <i class="bi bi-person-lines-fill fs-1 text-success"></i>
            <h4 class="mt-3">Autores</h4>
            <p>Gestionar información de autores.</p>
            <a href="{% url 'lista_autores' %}" class="btn btn-success">Entrar</a>
        </div>  
    </div>

    <!-- Multas -->
    <div class="col-md-3">
        <div class="card shadow-sm text-center p-3">
            <i class="bi bi-cash-stack fs-1 text-danger"></i>
            <h4 class="mt-3">Multas</h4>
            <p>Control de pagos y sanciones.</p>
            <a href="#" class="btn btn-danger">Entrar</a>
        </div>
    </div>

    <!-- Préstamos -->
    <div class="col-md-3">
        <div class="card shadow-sm text-center p-3">
            <i class="bi bi-arrow-left-right fs-1 text-warning"></i>
            <h4 class="mt-3">Préstamos</h4>
            <p>Registrar y gestionar préstamos.</p>
            <a href="{% url 'lista_prestamos' %}" class="btn btn-warning text-white">Entrar</a>
        </div>
    </div>

</div>
{% endblock  %}

gestion/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca - Panel Principal</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">

    <style>
        body {
            background: linear-gradient(to right, #eef2f3, #d9e4ec);
        }
        .navbar {
            background: #fd0dad;
        }
        .navbar-brand, .nav-link {
            color: white !important;
        }
        .card:hover {
            transform: translateY(-5px);
            transition: 0.3s ease;
        }
        footer {
            background: #fd0da1;
            color: white;
            margin-top: 40px;
            padding: 15px 0;
        }
    </style>
</head>

<body>

    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark shadow">
        <div class="container">
            <a class="navbar-brand fw-bold" href="#"><i class="bi bi-book-half"></i> Biblioteca</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menu">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="menu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="bi bi-journal-bookmark"></i> Libros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lista_autores' %}"><i class="bi bi-person-lines-fill"></i> Autores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="bi bi-cash-stack"></i> Multas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="bi bi-arrow-left-right"></i> Préstamos</a>
                    </li>
                    {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}"><i class="bi bi-arrow-left-right"></i> Ingresar</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <form method='post' action="{% url 'logout' %}">
                        {% csrf_token %}
                    <li class="nav-item">
                        <button type="submit"> Cerrar sesion</button>
                    </li>
                </form>
                {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- CONTENIDO PRINCIPAL -->
    <div class="container mt-5">
        <h1 class="text-center mb-4 fw-bold">Panel de Gestión de Biblioteca</h1>
        {% block contenido %}
        {% endblock %}
        
    </div>

    
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

gestion/templates/libros.html
{% extends "index.html" %}

<!-- Seccion de autores -->
{% block contenido %}
<h2> Libros </h2>
    <table style="border: 1px solid">
        <tr style="border: 1px solid">
            <td  style="border: 1px solid">Titulo</td>
            <td  style="border: 1px solid">Autor</td>
            <td  style="border: 1px solid">Disponible</td>
        </tr>
        {% for libro in libros %}
        <tr  style="border: 1px solid">
            <td  style="border: 1px solid">
                {{ libro.titulo }}
            </td>
            <td  style="border: 1px solid">
                {{ libro.autor }}
            </td>
            <td  style="border: 1px solid">
                {{ libro.disponible}}
            </td>
            </tr>
        {% endfor %}

    </table>

{% endblock %}

gestion/templates/libros_view.html
{% extends "index.html" %}

<!-- Seccion de autores -->
{% block contenido %}

<table style="border: 1px solid">
    <tr style="border: 1px solid">
        <td  style="border: 1px solid">Titulo</td>
        <td  style="border: 1px solid">Autor</td>
        <td  style="border: 1px solid">Disponible</td>
    </tr>
    {% for libro in libros %}
    <tr  style="border: 1px solid">
        <td  style="border: 1px solid">
            {{ libro.titulo }}
        </td>
        <td  style="border: 1px solid">
            {{ libro.autor }}
        </td>
        <td  style="border: 1px solid">
            {{ libro.disponible}}
        </td>
        </tr>
    {% endfor %}

</table>


{% if is_paginated %}
<div class="pagination">
    {% if page_obj.has_previous %}
    <a href="?page=1">Primera</a>
    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
    {% endif %}
    <span> {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
    <a href="?page={{ page_obj.paginator_num_pages }}">última</a>
    {% endif %}
    <span> {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>

</div>
{% endif %}
{% endblock %}

gestion/templates/multas.html
{% extends "index.html" %}

<!-- Seccion de autores -->
{% block contenido %}
<h2> Multas </h2>
    <table style="border: 1px solid">
        <tr style="border: 1px solid">
            <td  style="border: 1px solid">Prestamo</td>
            <td  style="border: 1px solid">Tipo</td>
            <td  style="border: 1px solid">Monto</td>
            <td  style="border: 1px solid">Pagada</td>
            <td  style="border: 1px solid">Fecha</td>
        </tr>
        {% for multa in multas %}
        <tr  style="border: 1px solid">
            <td  style="border: 1px solid">
                {{ multa.prestamo }}
            </td>
            <td  style="border: 1px solid">
                {{ multa.tipo }}
            </td>
            <td  style="border: 1px solid">
                {{ multa.monto}}
            </td>
            <td  style="border: 1px solid">
                {{ multa.pagada }}
            </td>
            <td  style="border: 1px solid">
                {{ multa.fecha}}
            </td>
            </tr>
        {% endfor %}

    </table>

{% endblock %}

gestion/templates/prestamos.html
{% extends "index.html" %}

<!-- Seccion de autores -->
{% block contenido %}
<h2> PRESTAMOS </h2>
    <table style="border: 1px solid">
        <tr style="border: 1px solid">
            <td  style="border: 1px solid">Libro</td>
            <td  style="border: 1px solid">Usuario</td>
            <td  style="border: 1px solid">fecha_prestamos</td>
            <td  style="border: 1px solid">fecha_max</td>
            <td  style="border: 1px solid">fecha_devolucion</td>
            <td  style="border: 1px solid">dias_retraso</td>
            <td  style="border: 1px solid">multa_retraso</td>

        </tr>
        {% for prestamo in prestamos %}
        <tr  style="border: 1px solid">
            <td  style="border: 1px solid">
                {{ prestamo.libro }}
            </td>
    
            <td  style="border: 1px solid">
                {{ prestamo.usuario}}
            </td>
            <td  style="border: 1px solid">
                {{ prestamo.fecha_prestamos}}
            </td>
            <td  style="border: 1px solid">
                {{ prestamo.fecha_max}}
            </td>
            <td  style="border: 1px solid">
                {{ prestamo.fecha_devolucion}}
            </td>
            <td  style="border: 1px solid">
                {{ prestamo.dias_retraso}}
            </td>
            <td  style="border: 1px solid">
                {{ prestamo.multa_retraso }}
            </td>
            </tr>
        {% endfor %}

    </table>

    <form>
        <a href="{% url 'crear_prestamo' %}" class="btn btn-success">Crear</a>
    </form>

{% endblock %}